name: branch_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: AleksanderMoosieno/Coffee-Machine-Kotlin-@main
      - name: Greetings
        run: echo "$(<greetings.txt)"
